### ISSUE TITLE
Profile chat option

### ISSUE THREAD

**Issue by andrewvdp** [relaycc/relay#6]
Instead of having the SEND A MESSAGE button on every card, it would be better to put the fixed launch button in the bottom right and have it persistent across profile navigations

**Comment by killthebuddh4** [comment]
The cards are the way they are because they might show up in different contexts. In general I think the following is going to be super important for a while: maximize card re-use, minimize card customization requirement.s We want to have extremely standard cards that can be used in a bunch of different contexts.

So let's do both for now:

* Add a launcher in the bottom right of the screen for the profiles page (`/u/0xADDRESS`)
* The launcher should be the user's avatar:
   * ENS avatar if it exists
   * else, Lens Avatar if it exists
   * els, Blockie

**Comment by andrewvdp** [comment]
That all sounds good but I think it needs to be clear what the launcher button does. If the launcher is the current profile avatar I don't this it is very clear that means "open a conversation with this person". I think we would either have to add some kind of chat bubble to it or make the launch button a chat bubble icon.
